const STORAGE_KEY='masrofati-data-v1';
const THEME_KEY='masrofati-theme';
const expenseCategories=['طعام ومشروبات','منزل','مواصلات','تسوق','ترفيه','صحة','تعليم','فواتير','أخرى'];
const incomeCategories=['راتب','دخل إضافي','مكافأة','استثمار','هدية','أخرى'];
const defaultData={transactions:[],obligations:[],savings:[]};
let data=loadData();
let selectedMonth=new Date(); selectedMonth.setDate(1);
let deferredPrompt=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('ar-SA',{style:'currency',currency:'SAR',maximumFractionDigits:2}).format(Number(n)||0);
const uid=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
function loadData(){try{return {...defaultData,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return structuredClone(defaultData)}}
function saveData(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));renderAll()}
function monthKey(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`}
function inSelectedMonth(date){return String(date).slice(0,7)===monthKey(selectedMonth)}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function setPage(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===id));window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav-item').forEach(b=>b.onclick=()=>setPage(b.dataset.page));$$('[data-page-link]').forEach(b=>b.onclick=()=>setPage(b.dataset.pageLink));
function monthSummary(){const tx=data.transactions.filter(t=>inSelectedMonth(t.date));const income=tx.filter(t=>t.type==='income').reduce((s,t)=>s+Number(t.amount),0);const expenses=tx.filter(t=>t.type==='expense').reduce((s,t)=>s+Number(t.amount),0);const obligations=data.obligations.reduce((s,o)=>s+Number(o.amount),0);const savings=data.savings.reduce((s,g)=>s+Number(g.monthly||0),0);return{tx,income,expenses,obligations,savings,remaining:income-expenses-obligations-savings}}
function renderDashboard(){const s=monthSummary();$('#monthTitle').textContent=new Intl.DateTimeFormat('ar-SA',{month:'long',year:'numeric'}).format(selectedMonth);$('#incomeValue').textContent=money(s.income);$('#expensesValue').textContent=money(s.expenses);$('#obligationsValue').textContent=money(s.obligations);$('#savingsValue').textContent=money(s.savings);$('#remainingValue').textContent=money(s.remaining);const used=s.income?Math.min(100,Math.max(0,((s.expenses+s.obligations+s.savings)/s.income)*100)):0;$('#budgetProgress').style.width=`${used}%`;$('#budgetMessage').textContent=s.income?(s.remaining>=0?`استخدمت ${used.toFixed(0)}% من دخلك.`:`تجاوزت دخلك بمقدار ${money(Math.abs(s.remaining))}.`):'أضف عملية دخل لبدء الحساب.';renderCategories($('#categoryBreakdown'),s.tx.filter(t=>t.type==='expense'));renderTransactionList($('#recentTransactions'),[...s.tx].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5),false)}
function categoryTotals(items){const map={};items.forEach(t=>map[t.category]=(map[t.category]||0)+Number(t.amount));return Object.entries(map).sort((a,b)=>b[1]-a[1])}
function renderCategories(el,items){const rows=categoryTotals(items);if(!rows.length){el.className='category-list empty-state';el.textContent='لا توجد بيانات.';return}el.className='category-list';const max=rows[0][1];el.innerHTML=rows.map(([name,val])=>`<div class="category-row"><strong>${escapeHtml(name)}</strong><span>${money(val)}</span><div class="bar"><i style="width:${(val/max)*100}%"></i></div></div>`).join('')}
function renderTransactionList(el,items,actions=true){if(!items.length){el.className='transaction-list empty-state';el.textContent='لا توجد عمليات.';return}el.className='transaction-list';el.innerHTML=items.map(t=>`<article class="transaction-item"><div class="transaction-icon ${t.type}">${t.type==='income'?'↓':'↑'}</div><div class="transaction-main"><strong>${escapeHtml(t.category)}</strong><small>${formatDate(t.date)}${t.note?' • '+escapeHtml(t.note):''}</small>${actions?`<div class="item-actions"><button class="mini-btn" data-edit-tx="${t.id}">تعديل</button><button class="mini-btn" data-delete-tx="${t.id}">حذف</button></div>`:''}</div><div class="amount ${t.type}">${t.type==='income'?'+':'-'}${money(t.amount)}</div></article>`).join('');if(actions){$$('[data-edit-tx]').forEach(b=>b.onclick=()=>openTransaction(data.transactions.find(t=>t.id===b.dataset.editTx)));$$('[data-delete-tx]').forEach(b=>b.onclick=()=>{if(confirm('حذف العملية؟')){data.transactions=data.transactions.filter(t=>t.id!==b.dataset.deleteTx);saveData();toast('تم الحذف')}})}}
function renderTransactions(){let items=[...data.transactions].sort((a,b)=>b.date.localeCompare(a.date));const type=$('#transactionTypeFilter').value,q=$('#transactionSearch').value.trim().toLowerCase();if(type!=='all')items=items.filter(t=>t.type===type);if(q)items=items.filter(t=>(t.category+' '+(t.note||'')).toLowerCase().includes(q));renderTransactionList($('#transactionsList'),items,true)}
function renderObligations(){const el=$('#obligationsList');if(!data.obligations.length){el.className='cards-list empty-state';el.textContent='لا توجد التزامات.';return}el.className='cards-list';el.innerHTML=data.obligations.map(o=>`<article class="card-item"><h3>${escapeHtml(o.name)}</h3><strong>${money(o.amount)}</strong><div class="card-meta"><span>يوم الاستحقاق: ${o.dueDay}</span><span>${o.isPaid?'تم السداد':'غير مسدد'}</span></div><div class="item-actions"><button class="mini-btn" data-toggle-ob="${o.id}">${o.isPaid?'إلغاء السداد':'تحديد كمسدد'}</button><button class="mini-btn" data-edit-ob="${o.id}">تعديل</button><button class="mini-btn" data-delete-ob="${o.id}">حذف</button></div></article>`).join('');$$('[data-toggle-ob]').forEach(b=>b.onclick=()=>{const o=data.obligations.find(x=>x.id===b.dataset.toggleOb);o.isPaid=!o.isPaid;saveData()});$$('[data-edit-ob]').forEach(b=>b.onclick=()=>openObligation(data.obligations.find(x=>x.id===b.dataset.editOb)));$$('[data-delete-ob]').forEach(b=>b.onclick=()=>{if(confirm('حذف الالتزام؟')){data.obligations=data.obligations.filter(x=>x.id!==b.dataset.deleteOb);saveData()}})}
function renderSavings(){const el=$('#savingsList');if(!data.savings.length){el.className='cards-list empty-state';el.textContent='لا توجد أهداف ادخار.';return}el.className='cards-list';el.innerHTML=data.savings.map(g=>{const p=Math.min(100,(Number(g.saved)/Number(g.target))*100||0);return`<article class="card-item"><h3>${escapeHtml(g.name)}</h3><div class="card-meta"><span>${money(g.saved)} من ${money(g.target)}</span><span>${p.toFixed(0)}%</span></div><div class="goal-progress"><i style="width:${p}%"></i></div><small class="muted">مساهمة شهرية: ${money(g.monthly)}</small><div class="item-actions"><button class="mini-btn" data-edit-save="${g.id}">تعديل</button><button class="mini-btn" data-delete-save="${g.id}">حذف</button></div></article>`}).join('');$$('[data-edit-save]').forEach(b=>b.onclick=()=>openSaving(data.savings.find(x=>x.id===b.dataset.editSave)));$$('[data-delete-save]').forEach(b=>b.onclick=()=>{if(confirm('حذف هدف الادخار؟')){data.savings=data.savings.filter(x=>x.id!==b.dataset.deleteSave);saveData()}})}
function renderReports(){const s=monthSummary();$('#savingRate').textContent=s.income?`${((s.savings/s.income)*100).toFixed(1)}%`:'0%';$('#spendingRate').textContent=s.income?`${(((s.expenses+s.obligations)/s.income)*100).toFixed(1)}%`:'0%';renderCategories($('#topCategories'),s.tx.filter(t=>t.type==='expense'))}
function renderAll(){renderDashboard();renderTransactions();renderObligations();renderSavings();renderReports()}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function formatDate(v){return new Intl.DateTimeFormat('ar-SA',{day:'numeric',month:'short',year:'numeric'}).format(new Date(v+'T12:00:00'))}
function fillCategorySelect(form,type){const sel=form.elements.category;const categories=type==='income'?incomeCategories:expenseCategories;sel.innerHTML=categories.map(c=>`<option>${c}</option>`).join('')}
function openTransaction(t=null){const f=$('#transactionForm');f.reset();f.elements.id.value=t?.id||'';f.elements.type.value=t?.type||'expense';fillCategorySelect(f,f.elements.type.value);if(t){f.elements.amount.value=t.amount;f.elements.category.value=t.category;f.elements.date.value=t.date;f.elements.paymentMethod.value=t.paymentMethod||'بطاقة';f.elements.note.value=t.note||''}else f.elements.date.value=new Date().toISOString().slice(0,10);$('#transactionDialogTitle').textContent=t?'تعديل العملية':'إضافة عملية';$('#transactionDialog').showModal()}
function openObligation(o=null){const f=$('#obligationForm');f.reset();f.elements.id.value=o?.id||'';if(o){f.elements.name.value=o.name;f.elements.amount.value=o.amount;f.elements.dueDay.value=o.dueDay;f.elements.isPaid.checked=!!o.isPaid}$('#obligationDialog').showModal()}
function openSaving(g=null){const f=$('#savingForm');f.reset();f.elements.id.value=g?.id||'';if(g){f.elements.name.value=g.name;f.elements.target.value=g.target;f.elements.saved.value=g.saved;f.elements.monthly.value=g.monthly}$('#savingDialog').showModal()}
$('#addTransactionBtn').onclick=()=>openTransaction();$('#addObligationBtn').onclick=()=>openObligation();$('#addSavingBtn').onclick=()=>openSaving();$$('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#transactionForm').elements.type.onchange=e=>fillCategorySelect($('#transactionForm'),e.target.value);
$('#transactionForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),id=f.get('id')||uid(),obj={id,type:f.get('type'),amount:Number(f.get('amount')),category:f.get('category'),date:f.get('date'),paymentMethod:f.get('paymentMethod'),note:f.get('note')};const i=data.transactions.findIndex(x=>x.id===id);if(i>=0)data.transactions[i]=obj;else data.transactions.push(obj);saveData();e.currentTarget.closest('dialog').close();toast('تم حفظ العملية')};
$('#obligationForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),id=f.get('id')||uid(),obj={id,name:f.get('name'),amount:Number(f.get('amount')),dueDay:Number(f.get('dueDay')),isPaid:f.get('isPaid')==='on'};const i=data.obligations.findIndex(x=>x.id===id);if(i>=0)data.obligations[i]=obj;else data.obligations.push(obj);saveData();e.currentTarget.closest('dialog').close();toast('تم حفظ الالتزام')};
$('#savingForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),id=f.get('id')||uid(),obj={id,name:f.get('name'),target:Number(f.get('target')),saved:Number(f.get('saved')),monthly:Number(f.get('monthly'))};const i=data.savings.findIndex(x=>x.id===id);if(i>=0)data.savings[i]=obj;else data.savings.push(obj);saveData();e.currentTarget.closest('dialog').close();toast('تم حفظ الهدف')};
$('#prevMonth').onclick=()=>{selectedMonth.setMonth(selectedMonth.getMonth()-1);renderAll()};$('#nextMonth').onclick=()=>{selectedMonth.setMonth(selectedMonth.getMonth()+1);renderAll()};$('#transactionTypeFilter').onchange=renderTransactions;$('#transactionSearch').oninput=renderTransactions;
function download(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$('#backupBtn').onclick=()=>download(`masrofati-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(data,null,2),'application/json');
$('#exportCsvBtn').onclick=()=>{const rows=[['النوع','المبلغ','التصنيف','التاريخ','طريقة الدفع','الملاحظة'],...data.transactions.map(t=>[t.type==='income'?'دخل':'مصروف',t.amount,t.category,t.date,t.paymentMethod,t.note])];const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');download('masrofati-transactions.csv',csv,'text/csv;charset=utf-8')};
$('#restoreInput').onchange=async e=>{try{const parsed=JSON.parse(await e.target.files[0].text());if(!parsed.transactions||!parsed.obligations||!parsed.savings)throw new Error();data=parsed;saveData();toast('تمت استعادة النسخة')}catch{alert('الملف غير صالح')}};
$('#clearDataBtn').onclick=()=>{if(confirm('سيتم حذف كل البيانات نهائيًا. هل أنت متأكد؟')){data=structuredClone(defaultData);saveData();toast('تم مسح البيانات')}};
const theme=localStorage.getItem(THEME_KEY);if(theme==='dark')document.documentElement.classList.add('dark');$('#themeBtn').onclick=()=>{document.documentElement.classList.toggle('dark');localStorage.setItem(THEME_KEY,document.documentElement.classList.contains('dark')?'dark':'light')};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));
renderAll();
